- readme.md
- src/components/ErrorPage/index.tsx
- src/components/PageBox/index.tsx
- src/modules/list/select.ts
- src/modules/store.ts
- src/pages/List/Base/index.tsx
- src/pages/List/Select/index.tsx
- src/pages/Result/403/index.tsx
- src/pages/Result/404/index.tsx
- src/pages/Result/500/index.tsx
> feat: 功能优化

- src/components/Card/index.module.less
- src/pages/Dashboard/Base/components/MiddleChart.tsx
- src/pages/Dashboard/Detail/components/PurchaseTrend.tsx
> fix:  修复1440屏幕出现滚动条

- src/components/Card/index.module.less
- src/pages/Dashboard/Base/components/MiddleChart.tsx
- src/pages/Dashboard/Detail/components/PurchaseTrend.tsx
> fix: fix layout, fixes #26

- package.json
- src/pages/Dashboard/Base/components/MiddleChart.tsx
1. 修复echarts配置错误
2. 修复 dev:linux 启动失败
> fix: 修复echarts配置错误

- package.json
> chore: upgrade tdesign-react to 0.27

- src/pages/Form/Base/index.module.less
- src/pages/Form/Base/index.tsx
> fix: fix 表单重置失败, fixes #34

- src/pages/Dashboard/Base/components/RankList.tsx
> fix: fixes #31

- src/pages/List/Select/index.tsx
> fix: 调整列表页表格与搜索间距

- src/layouts/components/Menu.module.less
- src/layouts/components/MenuLogo.tsx
> feat: logo点击跳转首页

- src/layouts/components/Container.tsx
- src/layouts/components/Content.tsx
- src/layouts/components/Menu.tsx
- src/layouts/index.tsx
- src/modules/global/index.ts
- 日常 bug 修复 路由切换导致菜单收起
- fix: https://github.com/Tencent/tdesign-react-starter/issues/44
> fix: menu collapse when route change

- src/pages/Dashboard/Base/chart.ts
> fix: 修复图表文字重叠, fixes #50

- package.json
- src/main.tsx
- 日常 bug 修复 构建产物丢失CSS Token
- 升级组件库指0.30.1
> fix: loss css token

- src/assets/svg/assets-result-maintenance.svg
- src/pages/Result/Maintenance/index.module.less
- src/pages/Result/Maintenance/index.tsx
- src/router/modules/result.ts
- 新特性提交
-  新增维护中页面
- https://github.com/Tencent/tdesign-vue-next-starter/issues/128
- feat: 新增维护中页面
> feat: add maintenance page

- src/router/modules/form.ts
> fix(typo): fix form menu title typo

- src/components/DatePicker/index.tsx
before
after
- fix: 修复datepicker重构后使用方法的改动
> fix(datepicker): follow  date-picker refactor

- src/pages/User/index.tsx
> chore: fix incorrect content

- src/pages/Result/BrowserIncompatible/index.module.less
- src/pages/Result/Maintenance/index.module.less
> fix: fix eslint

- src/layouts/components/Menu.tsx
- src/router/index.ts
- src/router/modules/others.ts
- src/utils/path.ts
- feat(Menu): 增加菜单hidden single功能
> feat: 增加菜单hidden single功能

- package-lock.json
- package.json
> feat: update modules

- README-zh_CN.md
> chore: add README in English

- package.json
> chore: fix submenu padding

- .env
- .env.development
- .env.site
> chore: fix node env

- package.json
> chore: release 0.3.0

- src/layouts/components/Footer.tsx
> chore: update copyright date

- .github/workflows/pull-request.yml
> chore: add site build workflow

- package.json
- src/layouts/components/Setting/PageConfig.module.less
- src/layouts/components/Setting/PageConfig.tsx
- src/layouts/components/Setting/index.module.less
- src/layouts/components/Setting/index.tsx
- src/main.tsx
> chore: fix page setting style

- src/pages/Form/Base/index.tsx
- fix(Form/Base): fix wrong form item rules
> fix(Form/Base): fix wrong formitem rules
